<?php

namespace App\Filament\Admin\Resources\AvailabilityResource\Pages;

use App\Filament\Admin\Resources\AvailabilityResource;
use Filament\Actions;
use Filament\Resources\Pages\ViewRecord;

class CalendarView extends ViewRecord
{
    protected static string $resource = AvailabilityResource::class;

    protected static string $view = 'filament.resources.availability-resource.pages.calendar-view';

    protected static ?string $title = 'Vue calendrier';

    public function mount(int|string $record): void
    {
        parent::mount($record); // TODO: Change the autogenerated stub
    }
}
